"use client";
import type { Metadata } from "next";
import { Rowdies } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import QueryProvider from "./providers/QueryProvider";

import { ModalProvider } from "./context/ModalContext";
// import { store } from "./store/store";
const rowdies = Rowdies({
  variable: "--font-rowdies",
  weight: ["300"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rowdies.className} antialiased  bg-linear-to-r from-[#120319] to-[#0b181c] h-screen`}
      >
        {/* wrap my app in the QueryProvider (for tanstack query) */}
        {/* a Provider is a react pattern based on React Context. It makes a value available to all descendant components without passing it as props. QueryClientProvider places teh queryClient into context ( here i have a separate QueryProvider in my providers/QueryProvider.tsx ). The provider connects hooks and components to the central cache and behaviors*/}
        {/* <Provider store={store}> */}
        <QueryProvider>
          <ModalProvider>
            <Navbar />
            {children}
            <Footer />
          </ModalProvider>
        </QueryProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
