"use client";
import type { Metadata } from "next";
import { Rowdies } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import QueryProvider from "./providers/QueryProvider";
import { Provider } from "react-redux";
import { store } from "./store/store";
const rowdies = Rowdies({
  variable: "--font-rowdies",
  weight: ["300"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rowdies.className} antialiased  bg-linear-to-r from-[#020309] to-[#0b181c]`}
      >
        <Provider store={store}>
          <QueryProvider>
            <Navbar />
            {children}
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
